#!/usr/bin/env bash
# setup nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > index.html
sudo rm /var/www/html/index.nginx-debian.html
sudo mv index.html /var/www/html/
sudo service nginx restart
