#!/usr/bin/env bash
# configures a new webserver with a redirect
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > index.html
sudo mv index.html /var/www/html/
str="\trewrite ^/redirect_me https://www.youtube.com/watch?v=oHg5SJYRHA0 permanent;\n}"
sudo sed -i "s@^}@$str@" /etc/nginx/sites-available/default
sudo service nginx restart
