#!/usr/bin/env bash
# configures a new webserver with a redirect
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > index.html
sudo mv index.html /var/www/html/

str="\trewrite ^/redirect_me https://www.youtube.com/watch?v=oHg5SJYRHA0 permanent;\n}"
sudo sed -i "s@^}@$str@" /etc/nginx/sites-available/default

sudo mkdir /var/www/error
echo "Ceci n'est pas une page" > custom_404.html
sudo mv custom_404.html /var/www/error/
str="\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/error;\n\t\tinternal;\n\t}\n}"
sudo sed -i "s@^}@$str@" /etc/nginx/sites-available/default

sudo service nginx restart
