#!/usr/bin/env bash
# I change ip things :P
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' ~/hosts.new
sed -i '1 i\8.8.8.8 facebook.com' ~/hosts.new
cp ~/hosts.new /etc/hosts
