#!/usr/bin/env bash
# configure nginx to run as nginx user
sudo service apache2 stop
sudo pkill apache2
sudo sed -i "s/#user.*/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod -R 777 /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
